### ISSUE TITLE
Spotify button hidden in the DOM

### ISSUE THREAD

**Issue by sirlisko** [sirLisko/shazamify#3]
I don't know why now the Shazam's track page has 2 duplicated articles, see below:
```
<article class="page-hd-v2 placeholder-v2 hide-placeholder">
  <div class="parts grid grid-vert-center"></div>
</article>
```
and
```
<article class="page-hd-v2 preview-avail">
  <div class="parts grid grid-vert-center"></div>
</article>
```
Obviously the Shazamify button is in the one hidden 😑

**Comment by sirLisko** [comment]
This should have been fixed by https://github.com/sirLisko/shazamify/commit/5e1d1a746c71f7ae600313baa01642c942f4da46.

The problem is that I can't test it locally as the login is not working `Unchecked runtime.lastError: Authorization page could not be loaded.` getting this error. But nothing changed, so I am pretty confused.

**Comment by sirlisko** [comment]
Fixed it! 🚀
